# Generated by Django 4.0.4 on 2022-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name', max_length=20)),
                ('Last_Name', models.CharField(help_text='Last Name', max_length=20)),
                ('Name_Movie', models.CharField(help_text='Movie', max_length=64)),
                ('Description', models.TextField(help_text='Description Movie')),
            ],
        ),
    ]
